version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app_static:/app/static  # Persists gifs, pdfs, screenshots
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
